FROM python:3.5

ENV PYTHONUNBUFFERED 1
ENV C_FORCE_ROOT true # Allow celery to run as root

# Dockerfile based on the official Celery
# https://github.com/docker-library/celery

# Prepare app folders & cmd
RUN mkdir -p /app/ /app/static
WORKDIR /app
CMD ["celery", "-A", "chalab.chacelery", "worker", "--loglevel=info"]

# Install the dependencies (rarely change)
ADD requirements.txt /app
RUN pip install -r requirements.txt

# Install the app code (change often)
ADD . /app

