FROM python:3.5

ENV PYTHONUNBUFFERED 1

# Dockerfile based on the official Celery
# https://github.com/docker-library/celery

# Prepare app folders & cmd
RUN pip install flower

CMD ["flower", \
     "--broker=amqp://admin:admin@rabbitmq:5672/chalab", \
     "--broker_api=http://admin:admin@rabbitmq:15672/api/", \
     "--port=5555"]