# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChallengeDescriptionModel',
            new_name='ChallengeModel',
        ),
    ]
