# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0002_auto_20160819_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.ChallengeModel')),
            ],
        ),
    ]
