# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0003_challengedatamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengedatamodel',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='wizard.ChallengeModel'),
        ),
    ]
