# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0004_auto_20160819_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengedatamodel',
            name='kind',
            field=models.CharField(choices=[('chalearn/adult', 'Chalearn: Adult'), ('chalearn/alexis', 'Chalearn: Alexis'), ('chalearn/christine', 'Chalearn: Christine'), ('chalearn/dilbert', 'Chalearn: Dilbert'), ('chalearn/dorothea', 'Chalearn: Dorothea'), ('chalearn/fabert', 'Chalearn: Fabert'), ('chalearn/jannis', 'Chalearn: Jannis'), ('chalearn/madeline', 'Chalearn: Madeline')], default='chalearn/adult', max_length=30),
        ),
        migrations.AddField(
            model_name='challengedatamodel',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
