# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import wizard.models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0005_auto_20160820_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnarFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_content', models.FileField(upload_to=wizard.models.StorageNameFactory('data', 'raw', 'columns'))),
                ('count', models.IntegerField()),
            ],
        ),
    ]
