# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wizard.models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0008_auto_20160825_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnarDocDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_content', models.FileField(upload_to=wizard.models.StorageNameFactory('data', 'raw', 'columns'))),
                ('count', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ColumnarNamesDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_content', models.FileField(upload_to=wizard.models.StorageNameFactory('data', 'raw', 'columns'))),
                ('count', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='axisdescriptionmodel',
            name='types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wizard.ColumnarTypesDefinition'),
        ),
        migrations.AddField(
            model_name='axisdescriptionmodel',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wizard.ColumnarDocDefinition'),
        ),
        migrations.AddField(
            model_name='axisdescriptionmodel',
            name='names',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wizard.ColumnarNamesDefinition'),
        ),
    ]
