# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0009_auto_20160825_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='axisdescriptionmodel',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='axisdescriptionmodel',
            name='doc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='axis', to='wizard.ColumnarDocDefinition'),
        ),
        migrations.AlterField(
            model_name='axisdescriptionmodel',
            name='names',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='axis', to='wizard.ColumnarNamesDefinition'),
        ),
        migrations.AlterField(
            model_name='axisdescriptionmodel',
            name='types',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='axis', to='wizard.ColumnarTypesDefinition'),
        ),
    ]
