# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0012_auto_20160825_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matrixmodel',
            old_name='columns',
            new_name='cols',
        ),
    ]
