# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0015_auto_20160825_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmodel',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
