# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0017_taskmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='train',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wizard.MatrixModel'),
        ),
    ]
