# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0018_taskmodel_train'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='train',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='input_test',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_tested', to='wizard.MatrixModel'),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='input_train',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_trained', to='wizard.MatrixModel'),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='input_valid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_validated', to='wizard.MatrixModel'),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='target_train',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_trained_target', to='wizard.MatrixModel'),
        ),
    ]
