# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0019_auto_20160825_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmodel',
            name='input',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataset_input', to='wizard.MatrixModel'),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='target',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataset_target', to='wizard.MatrixModel'),
        ),
    ]
