# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0021_matrixmodel_is_sparse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengedatamodel',
            name='challenge',
        ),
        migrations.AddField(
            model_name='challengemodel',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wizard.DatasetModel'),
        ),
        migrations.DeleteModel(
            name='ChallengeDataModel',
        ),
    ]
