# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0025_metricmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricmodel',
            name='classification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metricmodel',
            name='regression',
            field=models.BooleanField(default=False),
        ),
    ]
