# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0027_challengemodel_metric'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(default=None, null=True)),
                ('allow_reuse', models.BooleanField(default=False)),
                ('publicly_available', models.BooleanField(default=False)),
                ('max_submissions_per_day', models.IntegerField(default=None, null=True)),
                ('max_submissions', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='challengemodel',
            name='protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wizard.ProtocolModel'),
        ),
    ]
