# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0029_documentationpagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
