# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0030_documentationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationpagemodel',
            name='documentation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wizard.DocumentationModel'),
            preserve_default=False,
        ),
    ]
