# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0032_challengemodel_documentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengemodel',
            name='documentation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='wizard.DocumentationModel'),
        ),
    ]
