# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0033_auto_20160901_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolmodel',
            name='is_ready',
            field=models.BooleanField(default=True),
        ),
    ]
