# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0035_auto_20160901_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolmodel',
            name='short_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='protocolmodel',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='protocolmodel',
            name='max_submissions',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='protocolmodel',
            name='max_submissions_per_day',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
