# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0036_auto_20160901_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolmodel',
            name='short_url',
        ),
    ]
