# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 23:31
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0037_remove_protocolmodel_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationpagemodel',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
