# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 10:01
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0038_auto_20160901_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationpagemodel',
            name='rendered',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
