# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0041_auto_20160902_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmodel',
            name='authors',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='contact_name',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='contact_url',
            field=models.URLField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='keywords',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='license',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='preparation',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='resource_created',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='resource_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='challengemodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='data/logos/%Y/%m/%d/'),
        ),
    ]
