# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0042_auto_20160902_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengemodel',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentationmodel',
            name='is_ready',
            field=models.BooleanField(default=True),
        ),
    ]
