# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0044_remove_challengemodel_is_ready'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentationpagemodel',
            old_name='title',
            new_name='name',
        ),
    ]
