# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 14:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0045_auto_20160913_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationpagemodel',
            name='name',
            field=models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z', 32), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')]),
        ),
    ]
