# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 14:32
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0046_auto_20160913_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationpagemodel',
            name='rendered',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
