# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0047_auto_20160913_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='target_valid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_validated_target', to='wizard.MatrixModel'),
        ),
    ]
