# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0048_taskmodel_target_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challengemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
