# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0049_auto_20161020_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolmodel',
            name='max_submissions',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='protocolmodel',
            name='max_submissions_per_day',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
