# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0051_metricmodel_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
    ]
