# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0052_phasemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasemodel',
            name='challenge',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='wizard.ChallengeModel'),
            preserve_default=False,
        ),
    ]
