# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0053_phasemodel_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='target_test',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_tested_target', to='wizard.MatrixModel'),
        ),
    ]
