# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0054_taskmodel_target_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='test_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='train_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='valid_ratio',
            field=models.FloatField(null=True),
        ),
    ]
