# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0055_auto_20161022_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocolmodel',
            old_name='end_date',
            new_name='dev_end_date',
        ),
        migrations.RemoveField(
            model_name='protocolmodel',
            name='is_ready',
        ),
        migrations.AddField(
            model_name='protocolmodel',
            name='dev_start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='protocolmodel',
            name='final_end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='protocolmodel',
            name='final_start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
