# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0056_auto_20161024_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolmodel',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
