# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0057_protocolmodel_is_ready'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentationpagemodel',
            options={'ordering': ['pos']},
        ),
        migrations.AddField(
            model_name='documentationpagemodel',
            name='pos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='protocolmodel',
            name='dev_end_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Development phase end date'),
        ),
        migrations.AlterField(
            model_name='protocolmodel',
            name='dev_start_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Development phase start date'),
        ),
        migrations.AlterField(
            model_name='protocolmodel',
            name='final_end_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Final phase end date'),
        ),
        migrations.AlterField(
            model_name='protocolmodel',
            name='final_start_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Final phase start date'),
        ),
        migrations.AlterField(
            model_name='protocolmodel',
            name='max_submissions',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='protocolmodel',
            name='max_submissions_per_day',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
    ]
