# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0058_auto_20161029_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolmodel',
            name='dev_end_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Development phase end date'),
        ),
        migrations.AlterField(
            model_name='protocolmodel',
            name='dev_start_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Development phase start date'),
        ),
        migrations.AlterField(
            model_name='protocolmodel',
            name='final_end_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Final phase end date'),
        ),
        migrations.AlterField(
            model_name='protocolmodel',
            name='final_start_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Final phase start date'),
        ),
    ]
