# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import wizard.models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0061_auto_20161029_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselinemodel',
            name='submission',
            field=models.FileField(blank=True, null=True, upload_to=wizard.models.StorageNameFactory('baseline', 'submission'), verbose_name='baseline submission'),
        ),
    ]
