# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0062_baselinemodel_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselinemodel',
            name='submission',
            field=models.FileField(blank=True, null=True, upload_to='data/baseline/%Y/%m/%d/', verbose_name='baseline submission'),
        ),
    ]
