# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-19 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0065_auto_20161105_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolmodel',
            name='dev_end_date',
        ),
        migrations.RemoveField(
            model_name='protocolmodel',
            name='dev_execution_time_limit',
        ),
        migrations.RemoveField(
            model_name='protocolmodel',
            name='final_end_date',
        ),
        migrations.RemoveField(
            model_name='protocolmodel',
            name='final_execution_time_limit',
        ),
        migrations.AddField(
            model_name='protocolmodel',
            name='dev_phase_label',
            field=models.CharField(default='Development', max_length=128, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='protocolmodel',
            name='final_phase_label',
            field=models.CharField(default='Final', max_length=128, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='protocolmodel',
            name='dev_phase_description',
            field=models.TextField(default='Development phase: create your models and submit them or submit results on validation or test data; feed-back provided on validation set only.', max_length=2048, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='protocolmodel',
            name='dev_start_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='protocolmodel',
            name='final_phase_description',
            field=models.TextField(default='Final phase: non new submission, results on test set will be revealed when the organizers make them available.', max_length=2048, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='protocolmodel',
            name='final_start_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Start date'),
        ),
    ]
