# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0067_auto_20161119_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmodel',
            name='default_metric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wizard.MetricModel'),
        ),
    ]
