# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0068_datasetmodel_default_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricmodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
