# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0071_auto_20161124_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengemodel',
            name='documentation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='wizard.DocumentationModel'),
        ),
    ]
