# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-06 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0072_auto_20161125_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengemodel',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wizard.DatasetModel'),
        ),
        migrations.AlterField(
            model_name='challengemodel',
            name='metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wizard.MetricModel'),
        ),
        migrations.AlterField(
            model_name='datasetmodel',
            name='default_metric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wizard.MetricModel'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wizard.DatasetModel'),
        ),
    ]
