# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 18:56
from __future__ import unicode_literals

import chalab.tools.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0073_auto_20170606_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengemodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=chalab.tools.storage.save_to_logo),
        ),
    ]
