# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0077_auto_20170619_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
