# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0078_datasetmodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengemodel',
            name='build_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
