# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0079_challengemodel_build_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wizard.DatasetModel'),
        ),
    ]
