# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0080_auto_20170704_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetmodel',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
