# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0081_auto_20170705_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmodel',
            name='fixed_split',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='challengemodel',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wizard.TaskModel'),
        ),
    ]
