# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20170725_1004'),
        ('wizard', '0082_auto_20170706_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengemodel',
            name='origin_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group.GroupModel'),
        ),
    ]
