# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0083_challengemodel_origin_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengemodel',
            name='baseline',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge', to='wizard.BaselineModel'),
        ),
        migrations.AlterField(
            model_name='challengemodel',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wizard.DatasetModel'),
        ),
        migrations.AlterField(
            model_name='challengemodel',
            name='documentation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge', to='wizard.DocumentationModel'),
        ),
        migrations.AlterField(
            model_name='challengemodel',
            name='origin_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.GroupModel'),
        ),
        migrations.AlterField(
            model_name='challengemodel',
            name='protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge', to='wizard.ProtocolModel'),
        ),
    ]
