# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0084_auto_20170726_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixmodel',
            name='cols',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matrix_cols', to='wizard.AxisDescriptionModel'),
        ),
        migrations.AlterField(
            model_name='matrixmodel',
            name='rows',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matrix_rows', to='wizard.AxisDescriptionModel'),
        ),
    ]
