# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-19 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0086_auto_20170817_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationpagemodel',
            name='documentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation_pages', to='wizard.DocumentationModel'),
        ),
    ]
