# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 18:30
from __future__ import unicode_literals

import chalab.tools.storage
from django.db import migrations, models
import wizard.validators


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0087_auto_20170919_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengemodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=chalab.tools.storage.save_to_logo, validators=[wizard.validators.validate_file_extension_picture]),
        ),
    ]
