# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-24 17:26
from __future__ import unicode_literals

import chalab.tools.storage
from django.db import migrations, models
import django.db.models.deletion
import wizard.validators


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0087_auto_20171016_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionTaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingestion_program', models.FileField(blank=True, null=True, upload_to=chalab.tools.storage.save_to_ingestion, verbose_name='ingestion program')),
            ],
        ),
        migrations.AlterField(
            model_name='challengemodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=chalab.tools.storage.save_to_logo, validators=[wizard.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name='challengemodel',
            name='ingestion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge', to='wizard.IngestionTaskModel'),
        ),
    ]
