# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-30 20:12
from __future__ import unicode_literals

import chalab.tools.storage
from django.db import migrations, models
import django.db.models.deletion
import wizard.models
import wizard.validators


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0087_auto_20171016_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmodel',
            name='raw_zip',
            field=models.FileField(blank=True, null=True, upload_to=wizard.models.StorageNameFactory('data', 'raw', 'dataset')),
        ),
        migrations.AlterField(
            model_name='challengemodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=chalab.tools.storage.save_to_logo, validators=[wizard.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='challengemodel',
            name='metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='wizard.MetricModel'),
        ),
    ]
