# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-03 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0088_auto_20171024_1726'),
        ('wizard', '0088_auto_20171030_2012'),
    ]

    operations = [
    ]
