# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-09 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0088_auto_20171030_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengemodel',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='wizard.DatasetModel'),
        ),
        migrations.AlterField(
            model_name='datasetmodel',
            name='raw_zip',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='wizard.DatasetModel'),
        ),
    ]
