# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-17 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0091_datasetmodel_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmodel',
            name='raw_zip_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
