# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-17 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0092_datasetmodel_raw_zip_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmodel',
            name='show_date_on_display',
            field=models.BooleanField(default=False),
        ),
    ]
