# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0093_auto_20171122_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricmodel',
            name='display_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
