# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-17 17:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0093_datasetmodel_show_date_on_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetmodel',
            name='show_date_on_display',
        ),
        migrations.AddField(
            model_name='datasetmodel',
            name='resource_updated',
            field=models.DateField(blank=True, default=datetime.date(2017, 11, 17), null=True),
        ),
        migrations.AlterField(
            model_name='datasetmodel',
            name='resource_created',
            field=models.DateField(blank=True, default=datetime.date(2017, 11, 17), null=True),
        ),
    ]
