# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-17 17:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0094_auto_20171117_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnardocdefinition',
            name='raw_content_original_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='columnarnamesdefinition',
            name='raw_content_original_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='columnartypesdefinition',
            name='raw_content_original_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matrixmodel',
            name='raw_content_original_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datasetmodel',
            name='resource_created',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 17, 17, 43, 54, 785294, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='datasetmodel',
            name='resource_updated',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 11, 17, 17, 43, 54, 785620, tzinfo=utc), null=True),
        ),
    ]
