# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0094_metricmodel_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricmodel',
            name='label',
            field=models.CharField(default='', max_length=256),
        ),
    ]
