# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-11 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0096_metricmodel_resource_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricmodel',
            name='label',
            field=models.CharField(default='', max_length=20),
        ),
    ]
