# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-24 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='admins',
            field=models.ManyToManyField(db_table='admin_group', related_name='admin_of_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='default_dataset',
            field=models.ManyToManyField(db_table='dataset_group', to='wizard.DatasetModel'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='default_metric',
            field=models.ManyToManyField(db_table='metric_group', to='wizard.MetricModel'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='users',
            field=models.ManyToManyField(db_table='user_group', related_name='user_of_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
