# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-24 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20170724_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='default_dataset',
            field=models.ManyToManyField(db_table='dataset_group', null=True, to='wizard.DatasetModel'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='default_metric',
            field=models.ManyToManyField(db_table='metric_group', null=True, to='wizard.MetricModel'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='name',
            field=models.CharField(default='new group', max_length=30),
        ),
    ]
