# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-24 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20170724_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='default_dataset',
            field=models.ManyToManyField(db_table='dataset_group', to='wizard.DatasetModel'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='default_metric',
            field=models.ManyToManyField(db_table='metric_group', to='wizard.MetricModel'),
        ),
    ]
