# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 10:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0082_auto_20170706_1729'),
        ('group', '0004_auto_20170724_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='base_challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wizard.ChallengeModel'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='default_dataset',
            field=models.ManyToManyField(blank=True, db_table='dataset_group', to='wizard.DatasetModel'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='default_metric',
            field=models.ManyToManyField(blank=True, db_table='metric_group', to='wizard.MetricModel'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='name',
            field=models.CharField(default='New group', max_length=30),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='users',
            field=models.ManyToManyField(blank=True, db_table='user_group', related_name='user_of_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
