# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-17 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0086_auto_20170817_1235'),
        ('group', '0006_auto_20170817_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='base_challenge',
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wizard.ChallengeModel'),
        ),
    ]
