# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-25 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_auto_20170817_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
