# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bundler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodel',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_set', to='bundler.BundleTaskModel'),
        ),
    ]
