# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundler', '0002_auto_20160910_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundletaskmodel',
            name='state',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('started', 'Started'), ('cancelled', 'Cancelled'), ('finished', 'Finished'), ('failed', 'Failed')], max_length=10),
        ),
    ]
