# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bundler', '0003_auto_20160914_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bundletaskmodel',
            options={'ordering': ['-created']},
        ),
    ]
