# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-14 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bundler', '0007_auto_20170615_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundletaskmodel',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_tasks', to='wizard.ChallengeModel'),
        ),
    ]
