# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-14 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundler', '0008_auto_20171014_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundletaskmodel',
            name='current_task_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
